name: analog_photography_db
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  file_picker: ^8.1.2
  pdf: ^3.10.7
  permission_handler: ^11.1.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    # DATABASES
    - assets/databases/cameras_catalogue.db
    - assets/databases/chemicals_catalogue.db
    - assets/databases/dev_chart.db
    - assets/databases/dryers_catalogue.db
    - assets/databases/exposure_meters_catalogue.db
    - assets/databases/films_catalogue.db
    - assets/databases/film_scanners_catalogue.db
    - assets/databases/flashes_catalogue.db
    - assets/databases/lenses_catalogue.db
    - assets/databases/processors_catalogue.db

    # CAMERAS CATALOGUE ASSETS
    # Canon
    - assets/cameras_catalogue/canon/40/images/
    - assets/cameras_catalogue/canon/40/texts/
    - assets/cameras_catalogue/canon/42/images/
    - assets/cameras_catalogue/canon/42/texts/
    - assets/cameras_catalogue/canon/70/images/
    - assets/cameras_catalogue/canon/70/texts/
    - assets/cameras_catalogue/canon/72/images/
    - assets/cameras_catalogue/canon/72/texts/
    - assets/cameras_catalogue/canon/208/images/
    - assets/cameras_catalogue/canon/208/texts/
    - assets/cameras_catalogue/canon/210/images/
    - assets/cameras_catalogue/canon/210/texts/
    - assets/cameras_catalogue/canon/215/images/
    - assets/cameras_catalogue/canon/215/texts/
    - assets/cameras_catalogue/canon/251/images/
    - assets/cameras_catalogue/canon/251/texts/
    # Chinon
    - assets/cameras_catalogue/chinon/19/images/
    - assets/cameras_catalogue/chinon/19/texts/
    # Contax
    - assets/cameras_catalogue/contax/7/images/
    - assets/cameras_catalogue/contax/7/texts/
    - assets/cameras_catalogue/contax/17/images/
    - assets/cameras_catalogue/contax/17/texts/
    # Fujica
    - assets/cameras_catalogue/fujica/24/images/
    - assets/cameras_catalogue/fujica/24/texts/
    - assets/cameras_catalogue/fujica/59/images/
    - assets/cameras_catalogue/fujica/59/texts/
    # Konica
    - assets/cameras_catalogue/konica/14/images/
    - assets/cameras_catalogue/konica/14/texts/
    - assets/cameras_catalogue/konica/56/images/
    - assets/cameras_catalogue/konica/56/texts/
    # Leica
    - assets/cameras_catalogue/leica/25/images/
    - assets/cameras_catalogue/leica/25/texts/
    - assets/cameras_catalogue/leica/45/images/
    - assets/cameras_catalogue/leica/45/texts/
    # Minolta
    - assets/cameras_catalogue/minolta/176/images/
    - assets/cameras_catalogue/minolta/176/texts/
    - assets/cameras_catalogue/minolta/177/images/
    - assets/cameras_catalogue/minolta/177/texts/
    - assets/cameras_catalogue/minolta/180/images/
    - assets/cameras_catalogue/minolta/180/texts/
    # Nikon
    - assets/cameras_catalogue/nikon/27/images/
    - assets/cameras_catalogue/nikon/27/texts/
    - assets/cameras_catalogue/nikon/123/images/
    - assets/cameras_catalogue/nikon/123/texts/
    - assets/cameras_catalogue/nikon/126/images/
    - assets/cameras_catalogue/nikon/126/texts/
    # Topcon
    - assets/cameras_catalogue/topcon/26/images/
    - assets/cameras_catalogue/topcon/26/texts/
    - assets/cameras_catalogue/topcon/27/images/
    - assets/cameras_catalogue/topcon/27/texts/


    # ----------------------------------------------------

    - assets/images/developers/

    - assets/images/dryers/ilford/


    # FILMS CATALOGUE ASSETS
    # Agfa
    - assets/films_catalogue/agfa/1/images/
    - assets/films_catalogue/agfa/1/texts/


    # -----------------------------------------------------

    - assets/images/fixers/



    - assets/images/flashes/canon/


    - assets/images/lenses/asahi_pentax/


    - assets/images/meters/minolta/


    - assets/images/processors/jobo/


    - assets/images/scanners/minolta/

    - assets/texts/developer/

    - assets/texts/fixer/




